local a={"Banish",
"Corruption",
"Create Healthstone",
"Create Soulwell",
"Curse of Exhaustion",
"Curse of Tongues",
"Curse of Weakness",
"Demonic Circle",
"Demonic Circle: Teleport",
"Demonic Gateway",
"Drain Life",
"Eye of Kilrogg",
"Fear",
"Health Funnel",
"Ritual of Doom",
"Ritual of Summoning",
"Shadow Bolt",
"Shadowfury",
"Soul Rot",
"Soulshape",
"Soulstone",
"Subjugate Demon",
"Call Dreadstalkers",
"Demonbolt",
"Demonic Strength",
"Hand of Gul'dan",
"Implosion",
"Mortal Coil",
"Summon Demonic Tyrant",
"Summon Vilefiend",
"Bilescourge Bombers",
"Power Siphon",
"Doom",
"Soul Strike",
"Grimoire: Felguard",
"Nether Portal",
}